IntArrayDriver:  IntArray.o IntArrayDriver.o
	g++ -g -Wall -std=c++11 -o IntArrayDriver IntArray.o IntArrayDriver.o
IntArray.o:  IntArray.cpp IntArray.h
	g++ -g -Wall -std=c++11 -c IntArray.cpp
IntArrayDriver.o:  IntArrayDriver.cpp IntArray.h
	g++ -g -Wall -c IntArrayDriver.cpp